"use strict";
const TR={
 ro:{"Calendar":"Calendar","Shifts":"Ture","Done":"Gata","Cancel":"Anulează","Save":"Salvează","Close":"Închide","Back":"Înapoi","Add":"Adaugă","Off":"Liber","Edit":"Editează",
  "Estimated net pay for {m} {y}":"Salariu net estimat pentru {m} {y}","{n} work days":"{n} zile lucrate","{n} work day":"{n} zi lucrată","{n} leave":"{n} concediu","{h} h paid":"{h} h plătite","overtime":"ore supl.","premiums":"sporuri","Pay breakdown":"Detaliu plată","Base pay":"Salariu de bază","from net salary":"din salariul net","Day overtime":"Ore supl. zi","Night overtime":"Ore supl. noapte","Night premium":"Spor de noapte","Weekend premium":"Spor de weekend","Holiday premium":"Spor de sărbătoare","full shift":"tură completă","{h} night h":"{h} h noapte","{h} h":"{h} h","public holidays":"sărbători legale",
  "no shift":"fără tură","Paid leave":"Concediu plătit","Your shift templates":"Șabloanele tale de tură","Tap a shift to edit it, or swipe left to delete. Use + to create a custom one.":"Apasă o tură ca s-o editezi, sau glisează stânga ca s-o ștergi. Folosește + pentru una nouă.","No shifts yet":"Încă nicio tură","Tap + to create your first shift.":"Apasă + pentru prima ta tură.","night":"noapte","leave":"concediu","paid":"plătit","{m}m break":"{m}m pauză",
  "Settings":"Setări","Pay":"Plată","Salary & premiums":"Salariu & sporuri","{amt}/mo · {n} premiums on":"{amt}/lună · {n} sporuri active","Preferences":"Preferințe","Appearance":"Aspect","Light":"Luminos","Dark":"Întunecat","Automatic":"Automat","Region & format":"Regiune & format","Reminder before a shift":"Reamintire înainte de tură","Data":"Date","Export month (CSV)":"Export lună (CSV)","Backup & restore":"Backup & restaurare",
  "Salary":"Salariu","Net monthly salary":"Salariu net lunar","Net salary":"Salariu net","Premiums at your workplace":"Sporuri la locul tău de muncă","Overtime":"Ore suplimentare","Extra hours beyond the shift":"Ore peste program","Night shift":"Tură de noapte","Paid for the whole night shift":"Plătit pentru toată tura de noapte","Weekend":"Weekend","Public holiday":"Sărbătoare legală","Paid extra":"Plătit în plus","Turn a premium off to hide it from the HUB. Night overtime = overtime% + night%.":"Dezactivează un spor ca să-l ascunzi din HUB. Ore supl. noapte = ore supl.% + noapte%.",
  "Region":"Regiune","Country":"Țară","Picking a country sets its currency, week start, weekend, norm and public holidays — you can still fine-tune each below.":"Alegerea unei țări setează moneda, începutul săptămânii, weekendul, norma și sărbătorile — le poți ajusta apoi mai jos.","Currency":"Monedă","Number format":"Format numere","Device default":"Implicit dispozitiv","Week starts on":"Săptămâna începe","Monday":"Luni","Sunday":"Duminică","Saturday":"Sâmbătă","Weekend days":"Zile de weekend","Standard hours / day":"Ore standard / zi","Full-day norm":"Norma unei zile","Sets the monthly norm and the hourly rate":"Setează norma lunară și tariful orar","Custom holidays (repeat yearly)":"Sărbători personalizate (anuale)","No custom holidays yet":"Nicio sărbătoare personalizată","Holiday name":"Nume sărbătoare","Country holidays are approximate for planning; adjust any day in the calendar, and add your own recurring days here.":"Sărbătorile de țară sunt aproximative pentru planificare; ajustează orice zi în calendar și adaugă zilele tale aici.","Language":"Limbă",
  "Extra this day":"Extra în această zi","No shift":"Fără tură","weekend":"weekend","holiday":"sărbătoare","Overtime hours":"Ore suplimentare","Holiday":"Concediu","Public holiday · +{p}%":"Sărbătoare legală · +{p}%","Public holiday (auto)":"Sărbătoare legală (auto)","Mark as a holiday":"Marchează ca sărbătoare","Overtime & holiday pay are turned off in Settings → Salary.":"Orele supl. și plata de sărbătoare sunt dezactivate în Setări → Salariu.",
  "New shift":"Tură nouă","Edit shift":"Editează tura","Untitled":"Fără nume","total":"total","break":"pauză","Name":"Nume","Shift name":"Nume tură","Type":"Tip","Paid leave (holiday)":"Concediu plătit","Counts toward the month, paid as a normal day, no premiums or break":"Contează la normă, plătit ca zi normală, fără sporuri sau pauză","Schedule":"Program","Start":"Început","End":"Sfârșit","Break":"Pauză","Icon":"Pictogramă","Colour":"Culoare","Delete shift":"Șterge tura",
  "Copy CSV":"Copiază CSV","Downloads are blocked in preview; this copies to the clipboard.":"Descărcările sunt blocate în previzualizare; asta copiază în clipboard.",
  "Backup":"Backup","Export":"Export","Download":"Descarcă","Copy":"Copiază","Restore":"Restaurează","Choose a backup file":"Alege un fișier de backup","…or paste backup JSON here":"…sau lipește JSON-ul de backup aici","Restore backup":"Restaurează backup","Restoring replaces all current data on this device.":"Restaurarea înlocuiește toate datele de pe acest dispozitiv.",
  "Plan your shifts, track paid leave and see your estimated net pay — set up for any country in seconds.":"Planifică-ți turele, urmărește concediul și vezi salariul net estimat — configurat pentru orice țară în câteva secunde.","Get started":"Începe","Where do you work?":"Unde lucrezi?","We'll match your currency, week start, weekend and public holidays. You can change anything later.":"Potrivim moneda, începutul săptămânii, weekendul și sărbătorile. Poți schimba orice mai târziu.","Your monthly pay":"Salariul tău lunar","Enter your net monthly salary. It's your base — premiums and overtime add on top.":"Introdu salariul net lunar. E baza ta — sporurile și orele supl. se adaugă peste.","Start":"Start",
  "Restore backup?":"Restaurezi backup-ul?","This replaces all current shifts, salary and calendar data on this device. This cannot be undone.":"Asta înlocuiește toate turele, salariul și datele din calendar de pe acest dispozitiv. Nu se poate anula.","Delete shift?":"Ștergi tura?","Day saved":"Zi salvată","Shift created":"Tură creată","Shift updated":"Tură actualizată","Shift deleted":"Tură ștearsă","Backup restored":"Backup restaurat","Backup copied":"Backup copiat","CSV copied":"CSV copiat","Copy blocked here":"Copierea e blocată aici","Welcome to Shift Hub":"Bun venit în Shift Hub"},
 es:{"Calendar":"Calendario","Shifts":"Turnos","Done":"Listo","Cancel":"Cancelar","Save":"Guardar","Close":"Cerrar","Back":"Atrás","Add":"Añadir","Off":"Libre","Edit":"Editar",
  "Estimated net pay for {m} {y}":"Pago neto estimado de {m} {y}","{n} work days":"{n} días trabajados","{n} work day":"{n} día trabajado","{n} leave":"{n} de baja","{h} h paid":"{h} h pagadas","overtime":"horas extra","premiums":"pluses","Pay breakdown":"Desglose del pago","Base pay":"Salario base","from net salary":"del salario neto","Day overtime":"Extra de día","Night overtime":"Extra de noche","Night premium":"Plus de noche","Weekend premium":"Plus de fin de semana","Holiday premium":"Plus de festivo","full shift":"turno completo","{h} night h":"{h} h noche","{h} h":"{h} h","public holidays":"festivos",
  "no shift":"sin turno","Paid leave":"Baja pagada","Your shift templates":"Tus plantillas de turno","Tap a shift to edit it, or swipe left to delete. Use + to create a custom one.":"Toca un turno para editarlo o desliza para borrarlo. Usa + para crear uno.","No shifts yet":"Aún no hay turnos","Tap + to create your first shift.":"Toca + para crear tu primer turno.","night":"noche","leave":"baja","paid":"pagado","{m}m break":"{m}m descanso",
  "Settings":"Ajustes","Pay":"Pago","Salary & premiums":"Salario y pluses","{amt}/mo · {n} premiums on":"{amt}/mes · {n} pluses activos","Preferences":"Preferencias","Appearance":"Apariencia","Light":"Claro","Dark":"Oscuro","Automatic":"Automático","Region & format":"Región y formato","Reminder before a shift":"Aviso antes del turno","Data":"Datos","Export month (CSV)":"Exportar mes (CSV)","Backup & restore":"Copia y restaurar",
  "Salary":"Salario","Net monthly salary":"Salario neto mensual","Net salary":"Salario neto","Premiums at your workplace":"Pluses en tu trabajo","Overtime":"Horas extra","Extra hours beyond the shift":"Horas más allá del turno","Night shift":"Turno de noche","Paid for the whole night shift":"Pagado por todo el turno de noche","Weekend":"Fin de semana","Public holiday":"Festivo","Paid extra":"Pago extra","Turn a premium off to hide it from the HUB. Night overtime = overtime% + night%.":"Desactiva un plus para ocultarlo del HUB. Extra de noche = extra% + noche%.",
  "Region":"Región","Country":"País","Picking a country sets its currency, week start, weekend, norm and public holidays — you can still fine-tune each below.":"Elegir un país fija su moneda, inicio de semana, fin de semana, jornada y festivos — puedes ajustar cada uno abajo.","Currency":"Moneda","Number format":"Formato de número","Device default":"Predet. del dispositivo","Week starts on":"La semana empieza","Monday":"Lunes","Sunday":"Domingo","Saturday":"Sábado","Weekend days":"Días de fin de semana","Standard hours / day":"Horas estándar / día","Full-day norm":"Jornada completa","Sets the monthly norm and the hourly rate":"Define la jornada mensual y la tarifa por hora","Custom holidays (repeat yearly)":"Festivos propios (anuales)","No custom holidays yet":"Aún no hay festivos propios","Holiday name":"Nombre del festivo","Country holidays are approximate for planning; adjust any day in the calendar, and add your own recurring days here.":"Los festivos por país son aproximados; ajusta cualquier día en el calendario y añade los tuyos aquí.","Language":"Idioma",
  "Extra this day":"Extra este día","No shift":"Sin turno","weekend":"fin de semana","holiday":"festivo","Overtime hours":"Horas extra","Holiday":"Baja","Public holiday · +{p}%":"Festivo · +{p}%","Public holiday (auto)":"Festivo (auto)","Mark as a holiday":"Marcar como festivo","Overtime & holiday pay are turned off in Settings → Salary.":"El pago de extras y festivos está desactivado en Ajustes → Salario.",
  "New shift":"Nuevo turno","Edit shift":"Editar turno","Untitled":"Sin título","total":"total","break":"descanso","Name":"Nombre","Shift name":"Nombre del turno","Type":"Tipo","Paid leave (holiday)":"Baja pagada","Counts toward the month, paid as a normal day, no premiums or break":"Cuenta para el mes, pagado como día normal, sin pluses ni descanso","Schedule":"Horario","Start":"Inicio","End":"Fin","Break":"Descanso","Icon":"Icono","Colour":"Color","Delete shift":"Borrar turno",
  "Copy CSV":"Copiar CSV","Downloads are blocked in preview; this copies to the clipboard.":"Las descargas están bloqueadas en la vista previa; esto copia al portapapeles.",
  "Backup":"Copia","Export":"Exportar","Download":"Descargar","Copy":"Copiar","Restore":"Restaurar","Choose a backup file":"Elige un archivo de copia","…or paste backup JSON here":"…o pega aquí el JSON de la copia","Restore backup":"Restaurar copia","Restoring replaces all current data on this device.":"Restaurar reemplaza todos los datos de este dispositivo.",
  "Plan your shifts, track paid leave and see your estimated net pay — set up for any country in seconds.":"Planifica tus turnos, controla la baja pagada y ve tu pago neto estimado — listo para cualquier país en segundos.","Get started":"Empezar","Where do you work?":"¿Dónde trabajas?","We'll match your currency, week start, weekend and public holidays. You can change anything later.":"Ajustaremos tu moneda, inicio de semana, fin de semana y festivos. Puedes cambiar todo después.","Your monthly pay":"Tu pago mensual","Enter your net monthly salary. It's your base — premiums and overtime add on top.":"Introduce tu salario neto mensual. Es tu base — los pluses y las extras se suman.","Start":"Empezar",
  "Restore backup?":"¿Restaurar copia?","This replaces all current shifts, salary and calendar data on this device. This cannot be undone.":"Esto reemplaza todos los turnos, salario y datos del calendario en este dispositivo. No se puede deshacer.","Delete shift?":"¿Borrar turno?","Day saved":"Día guardado","Shift created":"Turno creado","Shift updated":"Turno actualizado","Shift deleted":"Turno borrado","Backup restored":"Copia restaurada","Backup copied":"Copia copiada","CSV copied":"CSV copiado","Copy blocked here":"Copia bloqueada aquí","Welcome to Shift Hub":"Bienvenido a Shift Hub"},
 de:{"Calendar":"Kalender","Shifts":"Schichten","Done":"Fertig","Cancel":"Abbrechen","Save":"Speichern","Close":"Schließen","Back":"Zurück","Add":"Hinzufügen","Off":"Frei","Edit":"Bearbeiten",
  "Estimated net pay for {m} {y}":"Geschätzter Nettolohn für {m} {y}","{n} work days":"{n} Arbeitstage","{n} work day":"{n} Arbeitstag","{n} leave":"{n} Urlaub","{h} h paid":"{h} Std. bezahlt","overtime":"Überstd.","premiums":"Zuschläge","Pay breakdown":"Lohnaufstellung","Base pay":"Grundlohn","from net salary":"vom Nettolohn","Day overtime":"Überstd. Tag","Night overtime":"Überstd. Nacht","Night premium":"Nachtzuschlag","Weekend premium":"Wochenendzuschlag","Holiday premium":"Feiertagszuschlag","full shift":"ganze Schicht","{h} night h":"{h} Std. Nacht","{h} h":"{h} Std.","public holidays":"Feiertage",
  "no shift":"keine Schicht","Paid leave":"Bezahlter Urlaub","Your shift templates":"Deine Schichtvorlagen","Tap a shift to edit it, or swipe left to delete. Use + to create a custom one.":"Tippe eine Schicht zum Bearbeiten oder wische zum Löschen. Mit + neu erstellen.","No shifts yet":"Noch keine Schichten","Tap + to create your first shift.":"Tippe + für deine erste Schicht.","night":"Nacht","leave":"Urlaub","paid":"bezahlt","{m}m break":"{m} Min. Pause",
  "Settings":"Einstellungen","Pay":"Lohn","Salary & premiums":"Lohn & Zuschläge","{amt}/mo · {n} premiums on":"{amt}/Mon. · {n} Zuschläge aktiv","Preferences":"Präferenzen","Appearance":"Darstellung","Light":"Hell","Dark":"Dunkel","Automatic":"Automatisch","Region & format":"Region & Format","Reminder before a shift":"Erinnerung vor Schicht","Data":"Daten","Export month (CSV)":"Monat exportieren (CSV)","Backup & restore":"Sichern & Wiederherstellen",
  "Salary":"Gehalt","Net monthly salary":"Monatliches Nettogehalt","Net salary":"Nettogehalt","Premiums at your workplace":"Zuschläge an deinem Arbeitsplatz","Overtime":"Überstunden","Extra hours beyond the shift":"Stunden über die Schicht hinaus","Night shift":"Nachtschicht","Paid for the whole night shift":"Bezahlt für die ganze Nachtschicht","Weekend":"Wochenende","Public holiday":"Feiertag","Paid extra":"Extra bezahlt","Turn a premium off to hide it from the HUB. Night overtime = overtime% + night%.":"Zuschlag ausschalten, um ihn im HUB zu verbergen. Überstd. Nacht = Überstd.% + Nacht%.",
  "Region":"Region","Country":"Land","Picking a country sets its currency, week start, weekend, norm and public holidays — you can still fine-tune each below.":"Ein Land setzt Währung, Wochenbeginn, Wochenende, Norm und Feiertage — du kannst alles unten anpassen.","Currency":"Währung","Number format":"Zahlenformat","Device default":"Gerätestandard","Week starts on":"Woche beginnt am","Monday":"Montag","Sunday":"Sonntag","Saturday":"Samstag","Weekend days":"Wochenendtage","Standard hours / day":"Standardstunden / Tag","Full-day norm":"Tagesnorm","Sets the monthly norm and the hourly rate":"Legt die Monatsnorm und den Stundensatz fest","Custom holidays (repeat yearly)":"Eigene Feiertage (jährlich)","No custom holidays yet":"Noch keine eigenen Feiertage","Holiday name":"Feiertagsname","Country holidays are approximate for planning; adjust any day in the calendar, and add your own recurring days here.":"Länderfeiertage sind Richtwerte; passe jeden Tag im Kalender an und füge hier eigene hinzu.","Language":"Sprache",
  "Extra this day":"Extra an diesem Tag","No shift":"Keine Schicht","weekend":"Wochenende","holiday":"Feiertag","Overtime hours":"Überstunden","Holiday":"Urlaub","Public holiday · +{p}%":"Feiertag · +{p}%","Public holiday (auto)":"Feiertag (auto)","Mark as a holiday":"Als Feiertag markieren","Overtime & holiday pay are turned off in Settings → Salary.":"Überstunden- und Feiertagslohn sind in Einstellungen → Gehalt deaktiviert.",
  "New shift":"Neue Schicht","Edit shift":"Schicht bearbeiten","Untitled":"Ohne Titel","total":"gesamt","break":"Pause","Name":"Name","Shift name":"Schichtname","Type":"Typ","Paid leave (holiday)":"Bezahlter Urlaub","Counts toward the month, paid as a normal day, no premiums or break":"Zählt zum Monat, bezahlt wie ein normaler Tag, ohne Zuschläge oder Pause","Schedule":"Zeitplan","Start":"Start","End":"Ende","Break":"Pause","Icon":"Symbol","Colour":"Farbe","Delete shift":"Schicht löschen",
  "Copy CSV":"CSV kopieren","Downloads are blocked in preview; this copies to the clipboard.":"Downloads sind in der Vorschau blockiert; dies kopiert in die Zwischenablage.",
  "Backup":"Backup","Export":"Export","Download":"Herunterladen","Copy":"Kopieren","Restore":"Wiederherstellen","Choose a backup file":"Backup-Datei wählen","…or paste backup JSON here":"…oder Backup-JSON hier einfügen","Restore backup":"Backup wiederherstellen","Restoring replaces all current data on this device.":"Wiederherstellen ersetzt alle Daten auf diesem Gerät.",
  "Plan your shifts, track paid leave and see your estimated net pay — set up for any country in seconds.":"Plane deine Schichten, verfolge bezahlten Urlaub und sieh deinen geschätzten Nettolohn — für jedes Land in Sekunden eingerichtet.","Get started":"Los geht's","Where do you work?":"Wo arbeitest du?","We'll match your currency, week start, weekend and public holidays. You can change anything later.":"Wir passen Währung, Wochenbeginn, Wochenende und Feiertage an. Du kannst alles später ändern.","Your monthly pay":"Dein Monatslohn","Enter your net monthly salary. It's your base — premiums and overtime add on top.":"Gib dein monatliches Nettogehalt ein. Das ist deine Basis — Zuschläge und Überstunden kommen dazu.","Start":"Start",
  "Restore backup?":"Backup wiederherstellen?","This replaces all current shifts, salary and calendar data on this device. This cannot be undone.":"Dies ersetzt alle Schichten, das Gehalt und die Kalenderdaten auf diesem Gerät. Nicht rückgängig zu machen.","Delete shift?":"Schicht löschen?","Day saved":"Tag gespeichert","Shift created":"Schicht erstellt","Shift updated":"Schicht aktualisiert","Shift deleted":"Schicht gelöscht","Backup restored":"Backup wiederhergestellt","Backup copied":"Backup kopiert","CSV copied":"CSV kopiert","Copy blocked here":"Kopieren hier blockiert","Welcome to Shift Hub":"Willkommen bei Shift Hub"},
 fr:{"Calendar":"Calendrier","Shifts":"Postes","Done":"OK","Cancel":"Annuler","Save":"Enregistrer","Close":"Fermer","Back":"Retour","Add":"Ajouter","Off":"Repos","Edit":"Modifier",
  "Estimated net pay for {m} {y}":"Salaire net estimé pour {m} {y}","{n} work days":"{n} jours travaillés","{n} work day":"{n} jour travaillé","{n} leave":"{n} congé","{h} h paid":"{h} h payées","overtime":"heures supp.","premiums":"primes","Pay breakdown":"Détail de la paie","Base pay":"Salaire de base","from net salary":"du salaire net","Day overtime":"Heures supp. jour","Night overtime":"Heures supp. nuit","Night premium":"Prime de nuit","Weekend premium":"Prime de week-end","Holiday premium":"Prime de jour férié","full shift":"poste complet","{h} night h":"{h} h nuit","{h} h":"{h} h","public holidays":"jours fériés",
  "no shift":"aucun poste","Paid leave":"Congé payé","Your shift templates":"Vos modèles de poste","Tap a shift to edit it, or swipe left to delete. Use + to create a custom one.":"Touchez un poste pour le modifier, ou glissez pour le supprimer. + pour en créer un.","No shifts yet":"Aucun poste pour l'instant","Tap + to create your first shift.":"Touchez + pour créer votre premier poste.","night":"nuit","leave":"congé","paid":"payé","{m}m break":"{m}m pause",
  "Settings":"Réglages","Pay":"Paie","Salary & premiums":"Salaire & primes","{amt}/mo · {n} premiums on":"{amt}/mois · {n} primes actives","Preferences":"Préférences","Appearance":"Apparence","Light":"Clair","Dark":"Sombre","Automatic":"Automatique","Region & format":"Région & format","Reminder before a shift":"Rappel avant un poste","Data":"Données","Export month (CSV)":"Exporter le mois (CSV)","Backup & restore":"Sauvegarde & restauration",
  "Salary":"Salaire","Net monthly salary":"Salaire net mensuel","Net salary":"Salaire net","Premiums at your workplace":"Primes de votre entreprise","Overtime":"Heures supplémentaires","Extra hours beyond the shift":"Heures au-delà du poste","Night shift":"Poste de nuit","Paid for the whole night shift":"Payé pour tout le poste de nuit","Weekend":"Week-end","Public holiday":"Jour férié","Paid extra":"Payé en plus","Turn a premium off to hide it from the HUB. Night overtime = overtime% + night%.":"Désactivez une prime pour la masquer du HUB. Heures supp. nuit = supp.% + nuit%.",
  "Region":"Région","Country":"Pays","Picking a country sets its currency, week start, weekend, norm and public holidays — you can still fine-tune each below.":"Choisir un pays règle sa devise, le début de semaine, le week-end, la norme et les jours fériés — ajustable ci-dessous.","Currency":"Devise","Number format":"Format des nombres","Device default":"Par défaut de l'appareil","Week starts on":"La semaine commence le","Monday":"Lundi","Sunday":"Dimanche","Saturday":"Samedi","Weekend days":"Jours de week-end","Standard hours / day":"Heures standard / jour","Full-day norm":"Norme journalière","Sets the monthly norm and the hourly rate":"Définit la norme mensuelle et le taux horaire","Custom holidays (repeat yearly)":"Jours fériés personnalisés (annuels)","No custom holidays yet":"Aucun jour férié personnalisé","Holiday name":"Nom du jour férié","Country holidays are approximate for planning; adjust any day in the calendar, and add your own recurring days here.":"Les jours fériés par pays sont approximatifs ; ajustez chaque jour dans le calendrier et ajoutez les vôtres ici.","Language":"Langue",
  "Extra this day":"Extra ce jour","No shift":"Aucun poste","weekend":"week-end","holiday":"férié","Overtime hours":"Heures supplémentaires","Holiday":"Congé","Public holiday · +{p}%":"Jour férié · +{p}%","Public holiday (auto)":"Jour férié (auto)","Mark as a holiday":"Marquer comme férié","Overtime & holiday pay are turned off in Settings → Salary.":"La paie des heures supp. et des jours fériés est désactivée dans Réglages → Salaire.",
  "New shift":"Nouveau poste","Edit shift":"Modifier le poste","Untitled":"Sans titre","total":"total","break":"pause","Name":"Nom","Shift name":"Nom du poste","Type":"Type","Paid leave (holiday)":"Congé payé","Counts toward the month, paid as a normal day, no premiums or break":"Compte pour le mois, payé comme un jour normal, sans primes ni pause","Schedule":"Horaire","Start":"Début","End":"Fin","Break":"Pause","Icon":"Icône","Colour":"Couleur","Delete shift":"Supprimer le poste",
  "Copy CSV":"Copier le CSV","Downloads are blocked in preview; this copies to the clipboard.":"Les téléchargements sont bloqués en aperçu ; ceci copie dans le presse-papiers.",
  "Backup":"Sauvegarde","Export":"Exporter","Download":"Télécharger","Copy":"Copier","Restore":"Restaurer","Choose a backup file":"Choisir un fichier de sauvegarde","…or paste backup JSON here":"…ou collez le JSON de sauvegarde ici","Restore backup":"Restaurer la sauvegarde","Restoring replaces all current data on this device.":"La restauration remplace toutes les données de cet appareil.",
  "Plan your shifts, track paid leave and see your estimated net pay — set up for any country in seconds.":"Planifiez vos postes, suivez vos congés payés et voyez votre salaire net estimé — configuré pour tout pays en quelques secondes.","Get started":"Commencer","Where do you work?":"Où travaillez-vous ?","We'll match your currency, week start, weekend and public holidays. You can change anything later.":"Nous adaptons votre devise, le début de semaine, le week-end et les jours fériés. Modifiable plus tard.","Your monthly pay":"Votre paie mensuelle","Enter your net monthly salary. It's your base — premiums and overtime add on top.":"Saisissez votre salaire net mensuel. C'est votre base — primes et heures supp. s'ajoutent.","Start":"Démarrer",
  "Restore backup?":"Restaurer la sauvegarde ?","This replaces all current shifts, salary and calendar data on this device. This cannot be undone.":"Ceci remplace tous les postes, le salaire et les données du calendrier sur cet appareil. Irréversible.","Delete shift?":"Supprimer le poste ?","Day saved":"Jour enregistré","Shift created":"Poste créé","Shift updated":"Poste mis à jour","Shift deleted":"Poste supprimé","Backup restored":"Sauvegarde restaurée","Backup copied":"Sauvegarde copiée","CSV copied":"CSV copié","Copy blocked here":"Copie bloquée ici","Welcome to Shift Hub":"Bienvenue sur Shift Hub"},
 it:{"Calendar":"Calendario","Shifts":"Turni","Done":"Fatto","Cancel":"Annulla","Save":"Salva","Close":"Chiudi","Back":"Indietro","Add":"Aggiungi","Off":"Libero","Edit":"Modifica",
  "Estimated net pay for {m} {y}":"Retribuzione netta stimata per {m} {y}","{n} work days":"{n} giorni lavorati","{n} work day":"{n} giorno lavorato","{n} leave":"{n} ferie","{h} h paid":"{h} h pagate","overtime":"straord.","premiums":"maggiorazioni","Pay breakdown":"Dettaglio paga","Base pay":"Paga base","from net salary":"dallo stipendio netto","Day overtime":"Straord. giorno","Night overtime":"Straord. notte","Night premium":"Magg. notturna","Weekend premium":"Magg. weekend","Holiday premium":"Magg. festiva","full shift":"turno intero","{h} night h":"{h} h notte","{h} h":"{h} h","public holidays":"festività",
  "no shift":"nessun turno","Paid leave":"Ferie pagate","Your shift templates":"I tuoi modelli di turno","Tap a shift to edit it, or swipe left to delete. Use + to create a custom one.":"Tocca un turno per modificarlo o scorri per eliminarlo. Usa + per crearne uno.","No shifts yet":"Ancora nessun turno","Tap + to create your first shift.":"Tocca + per creare il primo turno.","night":"notte","leave":"ferie","paid":"pagato","{m}m break":"{m}m pausa",
  "Settings":"Impostazioni","Pay":"Paga","Salary & premiums":"Stipendio e maggiorazioni","{amt}/mo · {n} premiums on":"{amt}/mese · {n} maggiorazioni attive","Preferences":"Preferenze","Appearance":"Aspetto","Light":"Chiaro","Dark":"Scuro","Automatic":"Automatico","Region & format":"Regione e formato","Reminder before a shift":"Promemoria prima del turno","Data":"Dati","Export month (CSV)":"Esporta mese (CSV)","Backup & restore":"Backup e ripristino",
  "Salary":"Stipendio","Net monthly salary":"Stipendio netto mensile","Net salary":"Stipendio netto","Premiums at your workplace":"Maggiorazioni sul lavoro","Overtime":"Straordinari","Extra hours beyond the shift":"Ore oltre il turno","Night shift":"Turno notturno","Paid for the whole night shift":"Pagato per l'intero turno notturno","Weekend":"Weekend","Public holiday":"Festività","Paid extra":"Pagato extra","Turn a premium off to hide it from the HUB. Night overtime = overtime% + night%.":"Disattiva una maggiorazione per nasconderla dall'HUB. Straord. notte = straord.% + notte%.",
  "Region":"Regione","Country":"Paese","Picking a country sets its currency, week start, weekend, norm and public holidays — you can still fine-tune each below.":"Scegliere un paese imposta valuta, inizio settimana, weekend, norma e festività — regolabili sotto.","Currency":"Valuta","Number format":"Formato numeri","Device default":"Predefinito dispositivo","Week starts on":"La settimana inizia di","Monday":"Lunedì","Sunday":"Domenica","Saturday":"Sabato","Weekend days":"Giorni di weekend","Standard hours / day":"Ore standard / giorno","Full-day norm":"Norma giornaliera","Sets the monthly norm and the hourly rate":"Imposta la norma mensile e la tariffa oraria","Custom holidays (repeat yearly)":"Festività personalizzate (annuali)","No custom holidays yet":"Nessuna festività personalizzata","Holiday name":"Nome festività","Country holidays are approximate for planning; adjust any day in the calendar, and add your own recurring days here.":"Le festività per paese sono indicative; regola ogni giorno nel calendario e aggiungi le tue qui.","Language":"Lingua",
  "Extra this day":"Extra questo giorno","No shift":"Nessun turno","weekend":"weekend","holiday":"festività","Overtime hours":"Ore di straordinario","Holiday":"Ferie","Public holiday · +{p}%":"Festività · +{p}%","Public holiday (auto)":"Festività (auto)","Mark as a holiday":"Segna come festività","Overtime & holiday pay are turned off in Settings → Salary.":"La paga per straordinari e festività è disattivata in Impostazioni → Stipendio.",
  "New shift":"Nuovo turno","Edit shift":"Modifica turno","Untitled":"Senza nome","total":"totale","break":"pausa","Name":"Nome","Shift name":"Nome turno","Type":"Tipo","Paid leave (holiday)":"Ferie pagate","Counts toward the month, paid as a normal day, no premiums or break":"Conta per il mese, pagato come giorno normale, senza maggiorazioni né pausa","Schedule":"Orario","Start":"Inizio","End":"Fine","Break":"Pausa","Icon":"Icona","Colour":"Colore","Delete shift":"Elimina turno",
  "Copy CSV":"Copia CSV","Downloads are blocked in preview; this copies to the clipboard.":"I download sono bloccati nell'anteprima; questo copia negli appunti.",
  "Backup":"Backup","Export":"Esporta","Download":"Scarica","Copy":"Copia","Restore":"Ripristina","Choose a backup file":"Scegli un file di backup","…or paste backup JSON here":"…o incolla qui il JSON di backup","Restore backup":"Ripristina backup","Restoring replaces all current data on this device.":"Il ripristino sostituisce tutti i dati su questo dispositivo.",
  "Plan your shifts, track paid leave and see your estimated net pay — set up for any country in seconds.":"Pianifica i turni, tieni traccia delle ferie e vedi la retribuzione netta stimata — pronto per ogni paese in pochi secondi.","Get started":"Inizia","Where do you work?":"Dove lavori?","We'll match your currency, week start, weekend and public holidays. You can change anything later.":"Adatteremo valuta, inizio settimana, weekend e festività. Puoi cambiare tutto dopo.","Your monthly pay":"La tua paga mensile","Enter your net monthly salary. It's your base — premiums and overtime add on top.":"Inserisci lo stipendio netto mensile. È la tua base — maggiorazioni e straordinari si aggiungono.","Start":"Inizia",
  "Restore backup?":"Ripristinare il backup?","This replaces all current shifts, salary and calendar data on this device. This cannot be undone.":"Sostituisce tutti i turni, lo stipendio e i dati del calendario su questo dispositivo. Irreversibile.","Delete shift?":"Eliminare il turno?","Day saved":"Giorno salvato","Shift created":"Turno creato","Shift updated":"Turno aggiornato","Shift deleted":"Turno eliminato","Backup restored":"Backup ripristinato","Backup copied":"Backup copiato","CSV copied":"CSV copiato","Copy blocked here":"Copia bloccata qui","Welcome to Shift Hub":"Benvenuto in Shift Hub"},
 pt:{"Calendar":"Calendário","Shifts":"Turnos","Done":"Concluído","Cancel":"Cancelar","Save":"Guardar","Close":"Fechar","Back":"Voltar","Add":"Adicionar","Off":"Folga","Edit":"Editar",
  "Estimated net pay for {m} {y}":"Salário líquido estimado para {m} {y}","{n} work days":"{n} dias trabalhados","{n} work day":"{n} dia trabalhado","{n} leave":"{n} de férias","{h} h paid":"{h} h pagas","overtime":"horas extra","premiums":"adicionais","Pay breakdown":"Detalhe do pagamento","Base pay":"Salário base","from net salary":"do salário líquido","Day overtime":"Extra de dia","Night overtime":"Extra de noite","Night premium":"Adicional noturno","Weekend premium":"Adicional de fim de semana","Holiday premium":"Adicional de feriado","full shift":"turno completo","{h} night h":"{h} h noite","{h} h":"{h} h","public holidays":"feriados",
  "no shift":"sem turno","Paid leave":"Férias pagas","Your shift templates":"Os teus modelos de turno","Tap a shift to edit it, or swipe left to delete. Use + to create a custom one.":"Toca num turno para editar ou desliza para apagar. Usa + para criar um.","No shifts yet":"Ainda sem turnos","Tap + to create your first shift.":"Toca + para criar o teu primeiro turno.","night":"noite","leave":"férias","paid":"pago","{m}m break":"{m}m pausa",
  "Settings":"Definições","Pay":"Pagamento","Salary & premiums":"Salário e adicionais","{amt}/mo · {n} premiums on":"{amt}/mês · {n} adicionais ativos","Preferences":"Preferências","Appearance":"Aparência","Light":"Claro","Dark":"Escuro","Automatic":"Automático","Region & format":"Região e formato","Reminder before a shift":"Lembrete antes do turno","Data":"Dados","Export month (CSV)":"Exportar mês (CSV)","Backup & restore":"Cópia e restauro",
  "Salary":"Salário","Net monthly salary":"Salário líquido mensal","Net salary":"Salário líquido","Premiums at your workplace":"Adicionais no teu trabalho","Overtime":"Horas extra","Extra hours beyond the shift":"Horas além do turno","Night shift":"Turno noturno","Paid for the whole night shift":"Pago pelo turno noturno completo","Weekend":"Fim de semana","Public holiday":"Feriado","Paid extra":"Pago extra","Turn a premium off to hide it from the HUB. Night overtime = overtime% + night%.":"Desativa um adicional para o ocultar do HUB. Extra de noite = extra% + noite%.",
  "Region":"Região","Country":"País","Picking a country sets its currency, week start, weekend, norm and public holidays — you can still fine-tune each below.":"Escolher um país define moeda, início da semana, fim de semana, norma e feriados — ajustáveis abaixo.","Currency":"Moeda","Number format":"Formato de número","Device default":"Predefinição do dispositivo","Week starts on":"A semana começa","Monday":"Segunda","Sunday":"Domingo","Saturday":"Sábado","Weekend days":"Dias de fim de semana","Standard hours / day":"Horas padrão / dia","Full-day norm":"Norma diária","Sets the monthly norm and the hourly rate":"Define a norma mensal e a taxa horária","Custom holidays (repeat yearly)":"Feriados personalizados (anuais)","No custom holidays yet":"Ainda sem feriados personalizados","Holiday name":"Nome do feriado","Country holidays are approximate for planning; adjust any day in the calendar, and add your own recurring days here.":"Os feriados por país são aproximados; ajusta qualquer dia no calendário e adiciona os teus aqui.","Language":"Idioma",
  "Extra this day":"Extra neste dia","No shift":"Sem turno","weekend":"fim de semana","holiday":"feriado","Overtime hours":"Horas extra","Holiday":"Férias","Public holiday · +{p}%":"Feriado · +{p}%","Public holiday (auto)":"Feriado (auto)","Mark as a holiday":"Marcar como feriado","Overtime & holiday pay are turned off in Settings → Salary.":"O pagamento de extras e feriados está desativado em Definições → Salário.",
  "New shift":"Novo turno","Edit shift":"Editar turno","Untitled":"Sem título","total":"total","break":"pausa","Name":"Nome","Shift name":"Nome do turno","Type":"Tipo","Paid leave (holiday)":"Férias pagas","Counts toward the month, paid as a normal day, no premiums or break":"Conta para o mês, pago como dia normal, sem adicionais nem pausa","Schedule":"Horário","Start":"Início","End":"Fim","Break":"Pausa","Icon":"Ícone","Colour":"Cor","Delete shift":"Apagar turno",
  "Copy CSV":"Copiar CSV","Downloads are blocked in preview; this copies to the clipboard.":"As transferências estão bloqueadas na pré-visualização; isto copia para a área de transferência.",
  "Backup":"Cópia","Export":"Exportar","Download":"Transferir","Copy":"Copiar","Restore":"Restaurar","Choose a backup file":"Escolher um ficheiro de cópia","…or paste backup JSON here":"…ou cola aqui o JSON da cópia","Restore backup":"Restaurar cópia","Restoring replaces all current data on this device.":"Restaurar substitui todos os dados neste dispositivo.",
  "Plan your shifts, track paid leave and see your estimated net pay — set up for any country in seconds.":"Planeia os teus turnos, acompanha as férias pagas e vê o salário líquido estimado — pronto para qualquer país em segundos.","Get started":"Começar","Where do you work?":"Onde trabalhas?","We'll match your currency, week start, weekend and public holidays. You can change anything later.":"Vamos adaptar a moeda, início da semana, fim de semana e feriados. Podes mudar tudo depois.","Your monthly pay":"O teu pagamento mensal","Enter your net monthly salary. It's your base — premiums and overtime add on top.":"Introduz o teu salário líquido mensal. É a tua base — adicionais e horas extra somam-se.","Start":"Começar",
  "Restore backup?":"Restaurar cópia?","This replaces all current shifts, salary and calendar data on this device. This cannot be undone.":"Isto substitui todos os turnos, salário e dados do calendário neste dispositivo. Não pode ser anulado.","Delete shift?":"Apagar turno?","Day saved":"Dia guardado","Shift created":"Turno criado","Shift updated":"Turno atualizado","Shift deleted":"Turno apagado","Backup restored":"Cópia restaurada","Backup copied":"Cópia copiada","CSV copied":"CSV copiado","Copy blocked here":"Cópia bloqueada aqui","Welcome to Shift Hub":"Bem-vindo ao Shift Hub"}
};
Object.assign(TR.ro,{"Run setup again":"Reia configurarea",});Object.assign(TR.es,{"Run setup again":"Repetir configuración",});Object.assign(TR.de,{"Run setup again":"Einrichtung erneut starten",});Object.assign(TR.fr,{"Run setup again":"Relancer la configuration",});Object.assign(TR.it,{"Run setup again":"Riesegui la configurazione",});Object.assign(TR.pt,{"Run setup again":"Repetir a configuração",});
Object.assign(TR.ro,{"This shift":"Această tură","will be removed and any days using it set to Off.":"va fi ștearsă, iar zilele care o folosesc devin Liber.","Backup saved":"Backup salvat","Backup downloaded":"Backup descărcat","Invalid backup file":"Fișier de backup invalid","Not a ShiftHub backup":"Nu e un backup ShiftHub","Paste a backup or pick a file":"Lipește un backup sau alege un fișier","Could not read file":"Fișierul nu a putut fi citit"});
Object.assign(TR.es,{"This shift":"Este turno","will be removed and any days using it set to Off.":"se eliminará y los días que lo usan pasarán a Libre.","Backup saved":"Copia guardada","Backup downloaded":"Copia descargada","Invalid backup file":"Archivo de copia no válido","Not a ShiftHub backup":"No es una copia de ShiftHub","Paste a backup or pick a file":"Pega una copia o elige un archivo","Could not read file":"No se pudo leer el archivo"});
Object.assign(TR.de,{"This shift":"Diese Schicht","will be removed and any days using it set to Off.":"wird entfernt; Tage damit werden auf Frei gesetzt.","Backup saved":"Backup gespeichert","Backup downloaded":"Backup heruntergeladen","Invalid backup file":"Ungültige Backup-Datei","Not a ShiftHub backup":"Kein ShiftHub-Backup","Paste a backup or pick a file":"Backup einfügen oder Datei wählen","Could not read file":"Datei konnte nicht gelesen werden"});
Object.assign(TR.fr,{"This shift":"Ce poste","will be removed and any days using it set to Off.":"sera supprimé et les jours qui l'utilisent passeront à Repos.","Backup saved":"Sauvegarde enregistrée","Backup downloaded":"Sauvegarde téléchargée","Invalid backup file":"Fichier de sauvegarde invalide","Not a ShiftHub backup":"Ce n'est pas une sauvegarde ShiftHub","Paste a backup or pick a file":"Collez une sauvegarde ou choisissez un fichier","Could not read file":"Impossible de lire le fichier"});
Object.assign(TR.it,{"This shift":"Questo turno","will be removed and any days using it set to Off.":"verrà rimosso e i giorni che lo usano passeranno a Libero.","Backup saved":"Backup salvato","Backup downloaded":"Backup scaricato","Invalid backup file":"File di backup non valido","Not a ShiftHub backup":"Non è un backup ShiftHub","Paste a backup or pick a file":"Incolla un backup o scegli un file","Could not read file":"Impossibile leggere il file"});
Object.assign(TR.pt,{"This shift":"Este turno","will be removed and any days using it set to Off.":"será removido e os dias que o usam passam a Folga.","Backup saved":"Cópia guardada","Backup downloaded":"Cópia transferida","Invalid backup file":"Ficheiro de cópia inválido","Not a ShiftHub backup":"Não é uma cópia ShiftHub","Paste a backup or pick a file":"Cola uma cópia ou escolhe um ficheiro","Could not read file":"Não foi possível ler o ficheiro"});
Object.assign(TR.ro,{"Add your shifts in the Calendar to see your estimated pay.":"Adaugă-ți turele în Calendar ca să-ți vezi salariul estimat.","Delete all data":"Șterge toate datele","This permanently erases all your shifts, settings and pay data on this device. This cannot be undone.":"Șterge definitiv toate turele, setările și datele de salariu de pe acest dispozitiv. Nu se poate anula.","Delete":"Șterge"});
Object.assign(TR.es,{"Add your shifts in the Calendar to see your estimated pay.":"Añade tus turnos en el Calendario para ver tu pago estimado.","Delete all data":"Eliminar todos los datos","This permanently erases all your shifts, settings and pay data on this device. This cannot be undone.":"Esto borra permanentemente todos tus turnos, ajustes y datos de pago en este dispositivo. No se puede deshacer.","Delete":"Eliminar"});
Object.assign(TR.de,{"Add your shifts in the Calendar to see your estimated pay.":"Füge deine Schichten im Kalender hinzu, um deinen geschätzten Lohn zu sehen.","Delete all data":"Alle Daten löschen","This permanently erases all your shifts, settings and pay data on this device. This cannot be undone.":"Dies löscht dauerhaft alle Schichten, Einstellungen und Lohndaten auf diesem Gerät. Das kann nicht rückgängig gemacht werden.","Delete":"Löschen"});
Object.assign(TR.fr,{"Add your shifts in the Calendar to see your estimated pay.":"Ajoute tes postes dans le Calendrier pour voir ta paie estimée.","Delete all data":"Supprimer toutes les données","This permanently erases all your shifts, settings and pay data on this device. This cannot be undone.":"Cela efface définitivement tous vos postes, réglages et données de paie sur cet appareil. Action irréversible.","Delete":"Supprimer"});
Object.assign(TR.it,{"Add your shifts in the Calendar to see your estimated pay.":"Aggiungi i tuoi turni nel Calendario per vedere la retribuzione stimata.","Delete all data":"Elimina tutti i dati","This permanently erases all your shifts, settings and pay data on this device. This cannot be undone.":"Questo elimina definitivamente tutti i turni, le impostazioni e i dati di paga su questo dispositivo. Non è reversibile.","Delete":"Elimina"});
Object.assign(TR.pt,{"Add your shifts in the Calendar to see your estimated pay.":"Adiciona os teus turnos no Calendário para veres o salário estimado.","Delete all data":"Apagar todos os dados","This permanently erases all your shifts, settings and pay data on this device. This cannot be undone.":"Isto apaga permanentemente todos os turnos, definições e dados de pagamento neste dispositivo. Não pode ser desfeito.","Delete":"Apagar"});
Object.assign(TR.ro,{"Which extras do you earn?":"Ce sporuri primești?","Turn on what applies at your job. You can change these anytime.":"Activează ce se aplică la jobul tău. Le poți schimba oricând.","Paid leave is always available.":"Concediul plătit este mereu disponibil."});
Object.assign(TR.es,{"Which extras do you earn?":"¿Qué extras ganas?","Turn on what applies at your job. You can change these anytime.":"Activa lo que se aplica a tu trabajo. Puedes cambiarlo cuando quieras.","Paid leave is always available.":"La baja pagada siempre está disponible."});
Object.assign(TR.de,{"Which extras do you earn?":"Welche Zuschläge bekommst du?","Turn on what applies at your job. You can change these anytime.":"Aktiviere, was auf deinen Job zutrifft. Du kannst das jederzeit ändern.","Paid leave is always available.":"Bezahlter Urlaub ist immer verfügbar."});
Object.assign(TR.fr,{"Which extras do you earn?":"Quelles primes touchez-vous ?","Turn on what applies at your job. You can change these anytime.":"Activez ce qui s'applique à votre travail. Vous pouvez les modifier à tout moment.","Paid leave is always available.":"Le congé payé est toujours disponible."});
Object.assign(TR.it,{"Which extras do you earn?":"Quali maggiorazioni ricevi?","Turn on what applies at your job. You can change these anytime.":"Attiva ciò che vale per il tuo lavoro. Puoi cambiarle quando vuoi.","Paid leave is always available.":"Le ferie pagate sono sempre disponibili."});
Object.assign(TR.pt,{"Which extras do you earn?":"Que extras recebes?","Turn on what applies at your job. You can change these anytime.":"Ativa o que se aplica ao teu trabalho. Podes mudar quando quiseres.","Paid leave is always available.":"A licença paga está sempre disponível."});
/* Capitalized hour unit (H) — German keeps its own "Std." abbreviation */
Object.assign(TR.ro,{"{h} H paid":"{h} H plătite","{h} H":"{h} H","{h} night H":"{h} H noapte","Paid hours":"Ore plătite","Hours paid per leave day":"Ore plătite pe zi de concediu"});
Object.assign(TR.es,{"{h} H paid":"{h} H pagadas","{h} H":"{h} H","{h} night H":"{h} H noche","Paid hours":"Horas pagadas","Hours paid per leave day":"Horas pagadas por día de baja"});
Object.assign(TR.de,{"{h} H paid":"{h} Std. bezahlt","{h} H":"{h} Std.","{h} night H":"{h} Std. Nacht","Paid hours":"Bezahlte Stunden","Hours paid per leave day":"Bezahlte Stunden pro Urlaubstag"});
Object.assign(TR.fr,{"{h} H paid":"{h} H payées","{h} H":"{h} H","{h} night H":"{h} H nuit","Paid hours":"Heures payées","Hours paid per leave day":"Heures payées par jour de congé"});
Object.assign(TR.it,{"{h} H paid":"{h} H pagate","{h} H":"{h} H","{h} night H":"{h} H notte","Paid hours":"Ore pagate","Hours paid per leave day":"Ore pagate per giorno di ferie"});
Object.assign(TR.pt,{"{h} H paid":"{h} H pagas","{h} H":"{h} H","{h} night H":"{h} H noite","Paid hours":"Horas pagas","Hours paid per leave day":"Horas pagas por dia de licença"});
/* v2.4 UX pass — new user-facing strings */
Object.assign(TR.ro,{"Today":"Azi","Tomorrow":"Mâine","Next shift":"Următoarea tură","This week":"Săptămâna asta","Nothing scheduled this month":"Nimic programat luna asta","Tap any day to paint a shift":"Apasă o zi ca să adaugi o tură","Duplicate yesterday":"Copiază de ieri","Assign a shift":"Alege o tură","Backup ready":"Backup gata"});
Object.assign(TR.es,{"Today":"Hoy","Tomorrow":"Mañana","Next shift":"Próximo turno","This week":"Esta semana","Nothing scheduled this month":"Nada programado este mes","Tap any day to paint a shift":"Toca un día para añadir un turno","Duplicate yesterday":"Copiar de ayer","Assign a shift":"Elige un turno","Backup ready":"Copia lista"});
Object.assign(TR.de,{"Today":"Heute","Tomorrow":"Morgen","Next shift":"Nächste Schicht","This week":"Diese Woche","Nothing scheduled this month":"Nichts geplant diesen Monat","Tap any day to paint a shift":"Tippe auf einen Tag, um eine Schicht einzutragen","Duplicate yesterday":"Von gestern kopieren","Assign a shift":"Schicht wählen","Backup ready":"Backup bereit"});
Object.assign(TR.fr,{"Today":"Aujourd'hui","Tomorrow":"Demain","Next shift":"Prochain poste","This week":"Cette semaine","Nothing scheduled this month":"Rien de prévu ce mois-ci","Tap any day to paint a shift":"Touchez un jour pour ajouter un poste","Duplicate yesterday":"Copier d'hier","Assign a shift":"Choisir un poste","Backup ready":"Sauvegarde prête"});
Object.assign(TR.it,{"Today":"Oggi","Tomorrow":"Domani","Next shift":"Prossimo turno","This week":"Questa settimana","Nothing scheduled this month":"Niente in programma questo mese","Tap any day to paint a shift":"Tocca un giorno per aggiungere un turno","Duplicate yesterday":"Copia da ieri","Assign a shift":"Scegli un turno","Backup ready":"Backup pronto"});
Object.assign(TR.pt,{"Today":"Hoje","Tomorrow":"Amanhã","Next shift":"Próximo turno","This week":"Esta semana","Nothing scheduled this month":"Nada agendado este mês","Tap any day to paint a shift":"Toca num dia para adicionar um turno","Duplicate yesterday":"Copiar de ontem","Assign a shift":"Escolher um turno","Backup ready":"Cópia pronta"});
/* B1 — repeat-week strings */
Object.assign(TR.ro,{"Repeat this week":"Repetă săptămâna asta","wks":"săpt.","Week copied forward":"Săptămână copiată","Nothing to copy":"Nimic de copiat"});
Object.assign(TR.es,{"Repeat this week":"Repetir esta semana","wks":"sem.","Week copied forward":"Semana copiada","Nothing to copy":"Nada que copiar"});
Object.assign(TR.de,{"Repeat this week":"Diese Woche wiederholen","wks":"Wo.","Week copied forward":"Woche kopiert","Nothing to copy":"Nichts zu kopieren"});
Object.assign(TR.fr,{"Repeat this week":"Répéter cette semaine","wks":"sem.","Week copied forward":"Semaine copiée","Nothing to copy":"Rien à copier"});
Object.assign(TR.it,{"Repeat this week":"Ripeti questa settimana","wks":"sett.","Week copied forward":"Settimana copiata","Nothing to copy":"Niente da copiare"});
Object.assign(TR.pt,{"Repeat this week":"Repetir esta semana","wks":"sem.","Week copied forward":"Semana copiada","Nothing to copy":"Nada para copiar"});
/* A4 — backup status strings */
Object.assign(TR.ro,{"Last backup":"Ultimul backup","never":"niciodată","Your data is saved only on this phone":"Datele tale sunt salvate doar pe acest telefon"});
Object.assign(TR.es,{"Last backup":"Última copia","never":"nunca","Your data is saved only on this phone":"Tus datos se guardan solo en este teléfono"});
Object.assign(TR.de,{"Last backup":"Letztes Backup","never":"nie","Your data is saved only on this phone":"Deine Daten liegen nur auf diesem Gerät"});
Object.assign(TR.fr,{"Last backup":"Dernière sauvegarde","never":"jamais","Your data is saved only on this phone":"Tes données sont enregistrées uniquement sur ce téléphone"});
Object.assign(TR.it,{"Last backup":"Ultimo backup","never":"mai","Your data is saved only on this phone":"I tuoi dati sono salvati solo su questo telefono"});
Object.assign(TR.pt,{"Last backup":"Última cópia","never":"nunca","Your data is saved only on this phone":"Os teus dados são guardados apenas neste telefone"});
/* C2 — effective net / premiums share */
Object.assign(TR.ro,{"Effective net":"Net efectiv"});Object.assign(TR.es,{"Effective net":"Neto efectivo"});Object.assign(TR.de,{"Effective net":"Effektiv netto"});Object.assign(TR.fr,{"Effective net":"Net effectif"});Object.assign(TR.it,{"Effective net":"Netto effettivo"});Object.assign(TR.pt,{"Effective net":"Líquido efetivo"});
/* C1 — income history */
Object.assign(TR.ro,{"Income history":"Istoric venituri"});Object.assign(TR.es,{"Income history":"Historial de ingresos"});Object.assign(TR.de,{"Income history":"Einkommensverlauf"});Object.assign(TR.fr,{"Income history":"Historique des revenus"});Object.assign(TR.it,{"Income history":"Storico guadagni"});Object.assign(TR.pt,{"Income history":"Histórico de ganhos"});
/* Onboarding — country selection */
Object.assign(TR.ro,{"Please select your country to continue":"Selectează-ți țara pentru a continua","Select country":"Selectează țara"});
Object.assign(TR.es,{"Please select your country to continue":"Selecciona tu país para continuar","Select country":"Selecciona un país"});
Object.assign(TR.de,{"Please select your country to continue":"Bitte wähle dein Land, um fortzufahren","Select country":"Land auswählen"});
Object.assign(TR.fr,{"Please select your country to continue":"Sélectionnez votre pays pour continuer","Select country":"Choisir un pays"});
Object.assign(TR.it,{"Please select your country to continue":"Seleziona il tuo paese per continuare","Select country":"Seleziona un paese"});
Object.assign(TR.pt,{"Please select your country to continue":"Seleciona o teu país para continuar","Select country":"Selecionar país"});
/* Pay breakdown — collapsible */
Object.assign(TR.ro,{"Total":"Total","Extra earnings":"Venituri extra","Tap to see every component":"Apasă pentru toate detaliile","Tap to hide details":"Apasă pentru a ascunde detaliile"});
Object.assign(TR.es,{"Total":"Total","Extra earnings":"Ingresos extra","Tap to see every component":"Toca para ver cada componente","Tap to hide details":"Toca para ocultar los detalles"});
Object.assign(TR.de,{"Total":"Gesamt","Extra earnings":"Zusätzliche Einnahmen","Tap to see every component":"Tippen für alle Details","Tap to hide details":"Tippen, um Details auszublenden"});
Object.assign(TR.fr,{"Total":"Total","Extra earnings":"Revenus supplémentaires","Tap to see every component":"Touchez pour tout le détail","Tap to hide details":"Touchez pour masquer les détails"});
Object.assign(TR.it,{"Total":"Totale","Extra earnings":"Guadagni extra","Tap to see every component":"Tocca per ogni voce","Tap to hide details":"Tocca per nascondere i dettagli"});
Object.assign(TR.pt,{"Total":"Total","Extra earnings":"Ganhos extra","Tap to see every component":"Toca para ver cada componente","Tap to hide details":"Toca para ocultar os detalhes"});
/* Onboarding — product intro (7 steps) */
Object.assign(TR.ro,{"Plan your shifts, track your hours and estimate your take-home pay.":"Planifică-ți turele, urmărește orele și estimează-ți salariul net.","Your salary":"Salariul tău","Tell us your net monthly pay. Shift Hub spreads it across the month's working days to estimate your take-home.":"Spune-ne salariul net lunar. Shift Hub îl distribuie pe zilele lucrătoare ca să-ți estimeze câștigul.","per month":"pe lună","Your shifts":"Turele tale","Morning, afternoon and night shifts are ready to use — or build your own with custom hours, breaks and colours.":"Turele de zi, după-amiază și noapte sunt gata — sau creează-ți propriile ture cu ore, pauze și culori.","Your calendar":"Calendarul tău","Tap any day to assign a shift, and edit it whenever your plans change. Long-press a day for a quick change.":"Apasă o zi ca să adaugi o tură și editeaz-o oricând. Apasă lung pentru o schimbare rapidă.","Automatic pay":"Plată automată","Overtime and night, weekend & holiday premiums are added automatically. Turn on what applies to you:":"Orele suplimentare și sporurile de noapte, weekend și sărbători se adaugă automat. Activează ce ți se aplică:","You can also add bonuses like a 13th salary later, in Settings.":"Poți adăuga și bonusuri precum al 13-lea salariu mai târziu, în Setări.","Make it yours":"Personalizează","Choose your country — it sets your currency, week start, weekend and public holidays. Language, theme and more are in Settings.":"Alege-ți țara — setează moneda, începutul săptămânii, weekendul și sărbătorile. Limba, tema și altele sunt în Setări.","You're all set":"Ești gata","Your estimated pay updates live as you plan. Ready when you are.":"Salariul estimat se actualizează pe măsură ce planifici. Când ești gata, pornim."});
Object.assign(TR.es,{"Plan your shifts, track your hours and estimate your take-home pay.":"Planifica tus turnos, controla tus horas y estima tu sueldo neto.","Your salary":"Tu salario","Tell us your net monthly pay. Shift Hub spreads it across the month's working days to estimate your take-home.":"Dinos tu salario neto mensual. Shift Hub lo reparte entre los días laborables para estimar lo que cobras.","per month":"al mes","Your shifts":"Tus turnos","Morning, afternoon and night shifts are ready to use — or build your own with custom hours, breaks and colours.":"Los turnos de mañana, tarde y noche están listos — o crea los tuyos con horas, descansos y colores.","Your calendar":"Tu calendario","Tap any day to assign a shift, and edit it whenever your plans change. Long-press a day for a quick change.":"Toca un día para asignar un turno y edítalo cuando cambien tus planes. Mantén pulsado para un cambio rápido.","Automatic pay":"Pago automático","Overtime and night, weekend & holiday premiums are added automatically. Turn on what applies to you:":"Las horas extra y los pluses de noche, fin de semana y festivos se añaden solos. Activa lo que te corresponda:","You can also add bonuses like a 13th salary later, in Settings.":"También puedes añadir extras como una paga extra más tarde, en Ajustes.","Make it yours":"Hazlo tuyo","Choose your country — it sets your currency, week start, weekend and public holidays. Language, theme and more are in Settings.":"Elige tu país — define moneda, inicio de semana, fin de semana y festivos. El idioma, el tema y más están en Ajustes.","You're all set":"Todo listo","Your estimated pay updates live as you plan. Ready when you are.":"Tu pago estimado se actualiza mientras planificas. Cuando quieras, empezamos."});
Object.assign(TR.de,{"Plan your shifts, track your hours and estimate your take-home pay.":"Plane deine Schichten, erfasse deine Stunden und schätze deinen Nettolohn.","Your salary":"Dein Gehalt","Tell us your net monthly pay. Shift Hub spreads it across the month's working days to estimate your take-home.":"Sag uns dein monatliches Nettogehalt. Shift Hub verteilt es auf die Arbeitstage, um deinen Verdienst zu schätzen.","per month":"pro Monat","Your shifts":"Deine Schichten","Morning, afternoon and night shifts are ready to use — or build your own with custom hours, breaks and colours.":"Früh-, Spät- und Nachtschichten sind startklar — oder erstelle eigene mit Zeiten, Pausen und Farben.","Your calendar":"Dein Kalender","Tap any day to assign a shift, and edit it whenever your plans change. Long-press a day for a quick change.":"Tippe auf einen Tag, um eine Schicht zuzuweisen, und ändere sie jederzeit. Lange drücken für eine schnelle Änderung.","Automatic pay":"Automatische Berechnung","Overtime and night, weekend & holiday premiums are added automatically. Turn on what applies to you:":"Überstunden sowie Nacht-, Wochenend- und Feiertagszuschläge werden automatisch addiert. Aktiviere, was zutrifft:","You can also add bonuses like a 13th salary later, in Settings.":"Boni wie ein 13. Gehalt kannst du später in den Einstellungen hinzufügen.","Make it yours":"Mach es zu deinem","Choose your country — it sets your currency, week start, weekend and public holidays. Language, theme and more are in Settings.":"Wähle dein Land — es legt Währung, Wochenstart, Wochenende und Feiertage fest. Sprache, Design und mehr sind in den Einstellungen.","You're all set":"Alles bereit","Your estimated pay updates live as you plan. Ready when you are.":"Dein geschätzter Lohn aktualisiert sich beim Planen. Los geht's, wann du willst."});
Object.assign(TR.fr,{"Plan your shifts, track your hours and estimate your take-home pay.":"Planifiez vos postes, suivez vos heures et estimez votre salaire net.","Your salary":"Votre salaire","Tell us your net monthly pay. Shift Hub spreads it across the month's working days to estimate your take-home.":"Indiquez votre salaire net mensuel. Shift Hub le répartit sur les jours ouvrés pour estimer ce que vous touchez.","per month":"par mois","Your shifts":"Vos postes","Morning, afternoon and night shifts are ready to use — or build your own with custom hours, breaks and colours.":"Les postes du matin, d'après-midi et de nuit sont prêts — ou créez les vôtres avec horaires, pauses et couleurs.","Your calendar":"Votre calendrier","Tap any day to assign a shift, and edit it whenever your plans change. Long-press a day for a quick change.":"Touchez un jour pour attribuer un poste, et modifiez-le à tout moment. Appui long pour un changement rapide.","Automatic pay":"Paie automatique","Overtime and night, weekend & holiday premiums are added automatically. Turn on what applies to you:":"Les heures supplémentaires et les primes de nuit, week-end et jours fériés sont ajoutées automatiquement. Activez ce qui vous concerne :","You can also add bonuses like a 13th salary later, in Settings.":"Vous pourrez aussi ajouter des primes comme un 13e mois plus tard, dans Réglages.","Make it yours":"Personnalisez","Choose your country — it sets your currency, week start, weekend and public holidays. Language, theme and more are in Settings.":"Choisissez votre pays — il définit la devise, le début de semaine, le week-end et les jours fériés. Langue, thème et plus dans Réglages.","You're all set":"Tout est prêt","Your estimated pay updates live as you plan. Ready when you are.":"Votre paie estimée se met à jour au fil de votre planning. Quand vous voulez, on démarre."});
Object.assign(TR.it,{"Plan your shifts, track your hours and estimate your take-home pay.":"Pianifica i turni, tieni traccia delle ore e stima lo stipendio netto.","Your salary":"Il tuo stipendio","Tell us your net monthly pay. Shift Hub spreads it across the month's working days to estimate your take-home.":"Indica lo stipendio netto mensile. Shift Hub lo distribuisce sui giorni lavorativi per stimare quanto prendi.","per month":"al mese","Your shifts":"I tuoi turni","Morning, afternoon and night shifts are ready to use — or build your own with custom hours, breaks and colours.":"I turni di mattina, pomeriggio e notte sono pronti — oppure creane di tuoi con orari, pause e colori.","Your calendar":"Il tuo calendario","Tap any day to assign a shift, and edit it whenever your plans change. Long-press a day for a quick change.":"Tocca un giorno per assegnare un turno e modificalo quando cambi i piani. Tieni premuto per un cambio rapido.","Automatic pay":"Calcolo automatico","Overtime and night, weekend & holiday premiums are added automatically. Turn on what applies to you:":"Straordinari e maggiorazioni notturne, del weekend e dei festivi si aggiungono da soli. Attiva ciò che ti riguarda:","You can also add bonuses like a 13th salary later, in Settings.":"Puoi aggiungere bonus come la tredicesima più tardi, nelle Impostazioni.","Make it yours":"Personalizza","Choose your country — it sets your currency, week start, weekend and public holidays. Language, theme and more are in Settings.":"Scegli il paese — imposta valuta, inizio settimana, weekend e festivi. Lingua, tema e altro sono nelle Impostazioni.","You're all set":"Tutto pronto","Your estimated pay updates live as you plan. Ready when you are.":"La paga stimata si aggiorna mentre pianifichi. Quando vuoi, si parte."});
Object.assign(TR.pt,{"Plan your shifts, track your hours and estimate your take-home pay.":"Planeia os teus turnos, acompanha as horas e estima o teu salário líquido.","Your salary":"O teu salário","Tell us your net monthly pay. Shift Hub spreads it across the month's working days to estimate your take-home.":"Diz-nos o teu salário líquido mensal. O Shift Hub distribui-o pelos dias úteis para estimar o que recebes.","per month":"por mês","Your shifts":"Os teus turnos","Morning, afternoon and night shifts are ready to use — or build your own with custom hours, breaks and colours.":"Os turnos de manhã, tarde e noite estão prontos — ou cria os teus com horas, pausas e cores.","Your calendar":"O teu calendário","Tap any day to assign a shift, and edit it whenever your plans change. Long-press a day for a quick change.":"Toca num dia para atribuir um turno e edita-o quando os planos mudarem. Prime longamente para uma mudança rápida.","Automatic pay":"Cálculo automático","Overtime and night, weekend & holiday premiums are added automatically. Turn on what applies to you:":"As horas extra e os prémios de noite, fim de semana e feriados são adicionados automaticamente. Ativa o que se aplica a ti:","You can also add bonuses like a 13th salary later, in Settings.":"Também podes adicionar bónus como o 13.º salário mais tarde, nas Definições.","Make it yours":"Personaliza","Choose your country — it sets your currency, week start, weekend and public holidays. Language, theme and more are in Settings.":"Escolhe o teu país — define moeda, início da semana, fim de semana e feriados. Idioma, tema e mais estão nas Definições.","You're all set":"Está tudo pronto","Your estimated pay updates live as you plan. Ready when you are.":"O salário estimado atualiza-se enquanto planeias. Quando quiseres, começamos."});
/* Settings — regrouped section headers */
Object.assign(TR.ro,{"Profile & pay":"Profil & plată","Region & calendar":"Regiune & calendar","Theme":"Temă"});
Object.assign(TR.es,{"Profile & pay":"Perfil y pago","Region & calendar":"Región y calendario","Theme":"Tema"});
Object.assign(TR.de,{"Profile & pay":"Profil & Lohn","Region & calendar":"Region & Kalender","Theme":"Design"});
Object.assign(TR.fr,{"Profile & pay":"Profil et paie","Region & calendar":"Région et calendrier","Theme":"Thème"});
Object.assign(TR.it,{"Profile & pay":"Profilo e paga","Region & calendar":"Regione e calendario","Theme":"Tema"});
Object.assign(TR.pt,{"Profile & pay":"Perfil e pagamento","Region & calendar":"Região e calendário","Theme":"Tema"});
/* Additional earnings (extra, non-shift pay) */
Object.assign(TR.ro,{"Additional bonuses":"Bonusuri suplimentare","{n} active":"{n} active","Attendance bonus, 13th salary and other extras that are not tied to a shift.":"Bonus de prezență, al 13-lea salariu și alte extra care nu țin de o tură.","Your extra earnings":"Veniturile tale extra","No extra earnings yet":"Încă niciun venit extra","Add a bonus":"Adaugă un bonus","Edit bonus":"Editează bonusul","Amount":"Sumă","e.g. 13th salary":"ex. al 13-lea salariu","Frequency":"Frecvență","Monthly":"Lunar","Weekly":"Săptămânal","Annually":"Anual","One-time":"O singură dată","Payment month":"Luna plății","Year":"An","Save bonus":"Salvează bonusul","Add bonus":"Adaugă bonus","Bonus":"Bonus","Enter a name and an amount":"Introdu un nume și o sumă","Weekly amounts are averaged into each month. Annual and one-time pay only in the chosen month.":"Sumele săptămânale se distribuie lunar. Cele anuale și unice se plătesc doar în luna aleasă."});
Object.assign(TR.es,{"Additional bonuses":"Bonos adicionales","{n} active":"{n} activos","Attendance bonus, 13th salary and other extras that are not tied to a shift.":"Bono de asistencia, paga extra y otros ingresos no ligados a un turno.","Your extra earnings":"Tus ingresos extra","No extra earnings yet":"Aún no hay ingresos extra","Add a bonus":"Añadir un bono","Edit bonus":"Editar bono","Amount":"Importe","e.g. 13th salary":"p. ej. paga extra","Frequency":"Frecuencia","Monthly":"Mensual","Weekly":"Semanal","Annually":"Anual","One-time":"Una vez","Payment month":"Mes de pago","Year":"Año","Save bonus":"Guardar bono","Add bonus":"Añadir bono","Bonus":"Bono","Enter a name and an amount":"Introduce un nombre y un importe","Weekly amounts are averaged into each month. Annual and one-time pay only in the chosen month.":"Los importes semanales se promedian por mes. Los anuales y únicos se pagan solo en el mes elegido."});
Object.assign(TR.de,{"Additional bonuses":"Zusätzliche Boni","{n} active":"{n} aktiv","Attendance bonus, 13th salary and other extras that are not tied to a shift.":"Anwesenheitsbonus, 13. Gehalt und andere Extras ohne Schichtbezug.","Your extra earnings":"Deine zusätzlichen Einnahmen","No extra earnings yet":"Noch keine zusätzlichen Einnahmen","Add a bonus":"Bonus hinzufügen","Edit bonus":"Bonus bearbeiten","Amount":"Betrag","e.g. 13th salary":"z. B. 13. Gehalt","Frequency":"Häufigkeit","Monthly":"Monatlich","Weekly":"Wöchentlich","Annually":"Jährlich","One-time":"Einmalig","Payment month":"Zahlungsmonat","Year":"Jahr","Save bonus":"Bonus speichern","Add bonus":"Bonus hinzufügen","Bonus":"Bonus","Enter a name and an amount":"Gib einen Namen und einen Betrag ein","Weekly amounts are averaged into each month. Annual and one-time pay only in the chosen month.":"Wöchentliche Beträge werden auf den Monat umgelegt. Jährliche und einmalige zahlen nur im gewählten Monat."});
Object.assign(TR.fr,{"Additional bonuses":"Primes supplémentaires","{n} active":"{n} actives","Attendance bonus, 13th salary and other extras that are not tied to a shift.":"Prime de présence, 13e mois et autres extras non liés à un poste.","Your extra earnings":"Vos revenus supplémentaires","No extra earnings yet":"Aucun revenu supplémentaire","Add a bonus":"Ajouter une prime","Edit bonus":"Modifier la prime","Amount":"Montant","e.g. 13th salary":"ex. 13e mois","Frequency":"Fréquence","Monthly":"Mensuel","Weekly":"Hebdomadaire","Annually":"Annuel","One-time":"Ponctuel","Payment month":"Mois de paiement","Year":"Année","Save bonus":"Enregistrer","Add bonus":"Ajouter","Bonus":"Prime","Enter a name and an amount":"Saisissez un nom et un montant","Weekly amounts are averaged into each month. Annual and one-time pay only in the chosen month.":"Les montants hebdomadaires sont lissés par mois. Les primes annuelles et ponctuelles ne paient que le mois choisi."});
Object.assign(TR.it,{"Additional bonuses":"Bonus aggiuntivi","{n} active":"{n} attivi","Attendance bonus, 13th salary and other extras that are not tied to a shift.":"Bonus presenza, tredicesima e altri extra non legati a un turno.","Your extra earnings":"I tuoi guadagni extra","No extra earnings yet":"Ancora nessun guadagno extra","Add a bonus":"Aggiungi un bonus","Edit bonus":"Modifica bonus","Amount":"Importo","e.g. 13th salary":"es. tredicesima","Frequency":"Frequenza","Monthly":"Mensile","Weekly":"Settimanale","Annually":"Annuale","One-time":"Una tantum","Payment month":"Mese di pagamento","Year":"Anno","Save bonus":"Salva bonus","Add bonus":"Aggiungi bonus","Bonus":"Bonus","Enter a name and an amount":"Inserisci un nome e un importo","Weekly amounts are averaged into each month. Annual and one-time pay only in the chosen month.":"Gli importi settimanali sono ripartiti sul mese. Annuali e una tantum pagano solo nel mese scelto."});
Object.assign(TR.pt,{"Additional bonuses":"Bónus adicionais","{n} active":"{n} ativos","Attendance bonus, 13th salary and other extras that are not tied to a shift.":"Bónus de assiduidade, 13.º salário e outros extras não ligados a um turno.","Your extra earnings":"Os teus ganhos extra","No extra earnings yet":"Ainda sem ganhos extra","Add a bonus":"Adicionar um bónus","Edit bonus":"Editar bónus","Amount":"Valor","e.g. 13th salary":"ex. 13.º salário","Frequency":"Frequência","Monthly":"Mensal","Weekly":"Semanal","Annually":"Anual","One-time":"Uma vez","Payment month":"Mês de pagamento","Year":"Ano","Save bonus":"Guardar bónus","Add bonus":"Adicionar bónus","Bonus":"Bónus","Enter a name and an amount":"Introduz um nome e um valor","Weekly amounts are averaged into each month. Annual and one-time pay only in the chosen month.":"Os valores semanais são distribuídos por mês. Anuais e únicos pagam só no mês escolhido."});
/* Storage failure */
Object.assign(TR.ro,{"Could not save on this device":"Nu s-a putut salva pe acest dispozitiv"});
Object.assign(TR.es,{"Could not save on this device":"No se pudo guardar en este dispositivo"});
Object.assign(TR.de,{"Could not save on this device":"Speichern auf diesem Gerät fehlgeschlagen"});
Object.assign(TR.fr,{"Could not save on this device":"Impossible d'enregistrer sur cet appareil"});
Object.assign(TR.it,{"Could not save on this device":"Impossibile salvare su questo dispositivo"});
Object.assign(TR.pt,{"Could not save on this device":"Não foi possível guardar neste dispositivo"});
/* Shift reminders */
Object.assign(TR.ro,{"Starts at {t}":"Începe la {t}","Allow notifications for Shift Hub in Settings":"Permite notificările pentru Shift Hub în Setări"});
Object.assign(TR.es,{"Starts at {t}":"Empieza a las {t}","Allow notifications for Shift Hub in Settings":"Permite las notificaciones de Shift Hub en Ajustes"});
Object.assign(TR.de,{"Starts at {t}":"Beginnt um {t}","Allow notifications for Shift Hub in Settings":"Erlaube Mitteilungen für Shift Hub in den Einstellungen"});
Object.assign(TR.fr,{"Starts at {t}":"Commence à {t}","Allow notifications for Shift Hub in Settings":"Autorisez les notifications de Shift Hub dans Réglages"});
Object.assign(TR.it,{"Starts at {t}":"Inizia alle {t}","Allow notifications for Shift Hub in Settings":"Consenti le notifiche di Shift Hub nelle Impostazioni"});
Object.assign(TR.pt,{"Starts at {t}":"Começa às {t}","Allow notifications for Shift Hub in Settings":"Permite as notificações do Shift Hub nas Definições"});
Object.assign(TR.ro,{"This backup was made by a newer version of Shift Hub":"Această copie de rezervă a fost creată de o versiune mai nouă de Shift Hub"});
Object.assign(TR.es,{"This backup was made by a newer version of Shift Hub":"Esta copia la creó una versión más reciente de Shift Hub"});
Object.assign(TR.de,{"This backup was made by a newer version of Shift Hub":"Dieses Backup wurde mit einer neueren Version von Shift Hub erstellt"});
Object.assign(TR.fr,{"This backup was made by a newer version of Shift Hub":"Cette sauvegarde a été créée par une version plus récente de Shift Hub"});
Object.assign(TR.it,{"This backup was made by a newer version of Shift Hub":"Questo backup è stato creato da una versione più recente di Shift Hub"});
Object.assign(TR.pt,{"This backup was made by a newer version of Shift Hub":"Esta cópia foi criada por uma versão mais recente do Shift Hub"});
Object.assign(TR.ro,{"Hold a shift and drag it to change the order.":"Ține apăsat pe o tură și trage-o pentru a schimba ordinea."});
Object.assign(TR.es,{"Hold a shift and drag it to change the order.":"Mantén pulsado un turno y arrástralo para cambiar el orden."});
Object.assign(TR.de,{"Hold a shift and drag it to change the order.":"Halte eine Schicht gedrückt und ziehe sie, um die Reihenfolge zu ändern."});
Object.assign(TR.fr,{"Hold a shift and drag it to change the order.":"Maintenez un poste appuyé et faites-le glisser pour changer l’ordre."});
Object.assign(TR.it,{"Hold a shift and drag it to change the order.":"Tieni premuto un turno e trascinalo per cambiare l’ordine."});
Object.assign(TR.pt,{"Hold a shift and drag it to change the order.":"Mantém premido um turno e arrasta-o para mudar a ordem."});
Object.assign(TR.ro,{"Move up":"Mută în sus","Move down":"Mută în jos"});
Object.assign(TR.es,{"Move up":"Subir","Move down":"Bajar"});
Object.assign(TR.de,{"Move up":"Nach oben","Move down":"Nach unten"});
Object.assign(TR.fr,{"Move up":"Monter","Move down":"Descendre"});
Object.assign(TR.it,{"Move up":"Sposta su","Move down":"Sposta giù"});
Object.assign(TR.pt,{"Move up":"Mover para cima","Move down":"Mover para baixo"});
Object.assign(TR.ro,{"Night hours paid":"Ore de noapte plătite"});
Object.assign(TR.es,{"Night hours paid":"Horas nocturnas pagadas"});
Object.assign(TR.de,{"Night hours paid":"Bezahlte Nachtstunden"});
Object.assign(TR.fr,{"Night hours paid":"Heures de nuit payées"});
Object.assign(TR.it,{"Night hours paid":"Ore notturne pagate"});
Object.assign(TR.pt,{"Night hours paid":"Horas noturnas pagas"});
